//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squad_Troubleshooter.Properties.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Squad_Troubleshooter.Properties.Language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squad Troubleshooter.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Squad logs to Desktop.
        /// </summary>
        internal static string COPY_OUTPUT1 {
            get {
                return ResourceManager.GetString("COPY_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying….
        /// </summary>
        internal static string COPY_OUTPUT2 {
            get {
                return ResourceManager.GetString("COPY_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Complete!.
        /// </summary>
        internal static string COPY_OUTPUT3 {
            get {
                return ResourceManager.GetString("COPY_OUTPUT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Windows Firewall.
        /// </summary>
        internal static string DISABLE_FIREWALL_BUTTON {
            get {
                return ResourceManager.GetString("DISABLE_FIREWALL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling the Windows firewall....
        /// </summary>
        internal static string DISABLE_OUTPUT1 {
            get {
                return ResourceManager.GetString("DISABLE_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Disabled.
        /// </summary>
        internal static string DISABLE_OUTPUT2 {
            get {
                return ResourceManager.GetString("DISABLE_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall Easy Anti-Cheat (EAC).
        /// </summary>
        internal static string EAC_BUTTON {
            get {
                return ResourceManager.GetString("EAC_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows Firewall.
        /// </summary>
        internal static string ENABLE_FIREWALL_BUTTON {
            get {
                return ResourceManager.GetString("ENABLE_FIREWALL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling the Windows firewall....
        /// </summary>
        internal static string ENABLE_OUTPUT1 {
            get {
                return ResourceManager.GetString("ENABLE_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firewall Enabled.
        /// </summary>
        internal static string ENABLE_OUTPUT2 {
            get {
                return ResourceManager.GetString("ENABLE_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FILE_MENU_EXIT {
            get {
                return ResourceManager.GetString("FILE_MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FILE_MENU_PARENT {
            get {
                return ResourceManager.GetString("FILE_MENU_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Windows Event Log.
        /// </summary>
        internal static string GENERATE_BUTTON {
            get {
                return ResourceManager.GetString("GENERATE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating log files….
        /// </summary>
        internal static string GENERATING_OUTPUT1 {
            get {
                return ResourceManager.GetString("GENERATING_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files have been generated and are now on your desktop.
        /// </summary>
        internal static string GENERATING_OUTPUT2 {
            get {
                return ResourceManager.GetString("GENERATING_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log is saved as.
        /// </summary>
        internal static string GENERATING_OUTPUT3 {
            get {
                return ResourceManager.GetString("GENERATING_OUTPUT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send all log files to support@joinsquad.com.
        /// </summary>
        internal static string GENERATING_OUTPUT4 {
            get {
                return ResourceManager.GetString("GENERATING_OUTPUT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are experiancing game crashes when using the Server Browser in game copy the following URL and visit the forums:.
        /// </summary>
        internal static string GET_HELP_OUTPUT1 {
            get {
                return ResourceManager.GetString("GET_HELP_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://goo.gl/yvTOfS.
        /// </summary>
        internal static string GET_HELP_OUTPUT2 {
            get {
                return ResourceManager.GetString("GET_HELP_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No binaries for vc_redist.x64.exe (2013)....
        /// </summary>
        internal static string INSTALL_VCREDIST_2013_ERROR_OUTPUT1 {
            get {
                return ResourceManager.GetString("INSTALL_VCREDIST_2013_ERROR_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping vc_redist.x64.exe (2013) install….
        /// </summary>
        internal static string INSTALL_VCREDIST_2013_ERROR_OUTPUT2 {
            get {
                return ResourceManager.GetString("INSTALL_VCREDIST_2013_ERROR_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing vc_redist.x64.exe (2013)....
        /// </summary>
        internal static string INSTALL_VCREDIST_2013_OUTPUT1 {
            get {
                return ResourceManager.GetString("INSTALL_VCREDIST_2013_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC Redistributable (2013) installation complete.
        /// </summary>
        internal static string INSTALL_VCREDIST_2013_OUTPUT2 {
            get {
                return ResourceManager.GetString("INSTALL_VCREDIST_2013_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No binaries for vc_redist.x64.exe (2015)....
        /// </summary>
        internal static string INSTALL_VCREDIST_2015_ERROR_OUTPUT1 {
            get {
                return ResourceManager.GetString("INSTALL_VCREDIST_2015_ERROR_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping vc_redist.x64.exe (2015) install....
        /// </summary>
        internal static string INSTALL_VCREDIST_2015_ERROR_OUTPUT2 {
            get {
                return ResourceManager.GetString("INSTALL_VCREDIST_2015_ERROR_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing vc_redist.x64.exe (2015)....
        /// </summary>
        internal static string INSTALL_VCREDIST_2015_OUTPUT1 {
            get {
                return ResourceManager.GetString("INSTALL_VCREDIST_2015_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VC Redistributable (2015) installation complete.
        /// </summary>
        internal static string INSTALL_VCREDIST_2015_OUTPUT2 {
            get {
                return ResourceManager.GetString("INSTALL_VCREDIST_2015_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string LANGUAGES_MENU_CHINESE {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_CHINESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string LANGUAGES_MENU_DUTCH {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LANGUAGES_MENU_ENGLISH {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string LANGUAGES_MENU_FRENCH {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_FRENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string LANGUAGES_MENU_GERMAN {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string LANGUAGES_MENU_PARENT {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string LANGUAGES_MENU_POLISH {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_POLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LANGUAGES_MENU_RUSSIAN {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string LANGUAGES_MENU_SPANISH {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_SPANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string LANGUAGES_MENU_SWEDISH {
            get {
                return ResourceManager.GetString("LANGUAGES_MENU_SWEDISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Squad Logs to Desktop.
        /// </summary>
        internal static string LOGS_BUTTON {
            get {
                return ResourceManager.GetString("LOGS_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuke AppData Config Files.
        /// </summary>
        internal static string NUKE_BUTTON {
            get {
                return ResourceManager.GetString("NUKE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData directory.
        /// </summary>
        internal static string NUKE_OUTPUT1 {
            get {
                return ResourceManager.GetString("NUKE_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been successfully nuked.
        /// </summary>
        internal static string NUKE_OUTPUT2 {
            get {
                return ResourceManager.GetString("NUKE_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No binaries for EasyAntiCheat_Setup.exe....
        /// </summary>
        internal static string REINSTALL_ERROR_OUTPUT1 {
            get {
                return ResourceManager.GetString("REINSTALL_ERROR_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping EasyAntiCheat_Setup.exe install....
        /// </summary>
        internal static string REINSTALL_ERROR_OUTPUT2 {
            get {
                return ResourceManager.GetString("REINSTALL_ERROR_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing EasyAntiCheat_Setup.exe....
        /// </summary>
        internal static string REINSTALL_OUTPUT1 {
            get {
                return ResourceManager.GetString("REINSTALL_OUTPUT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAC installation complete.
        /// </summary>
        internal static string REINSTALL_OUTPUT2 {
            get {
                return ResourceManager.GetString("REINSTALL_OUTPUT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help with game crashing on server browser.
        /// </summary>
        internal static string SERVER_BROWSER_BUTTON {
            get {
                return ResourceManager.GetString("SERVER_BROWSER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        internal static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install VC Redistributable 2013 + 2015.
        /// </summary>
        internal static string VCREDIST_BUTTON {
            get {
                return ResourceManager.GetString("VCREDIST_BUTTON", resourceCulture);
            }
        }
    }
}
